services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    ports:
      - '9100:9100'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 9100
      KC_LOG_CONSOLE_COLOR: 'true'
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -ex
        cp /opt/keycloak/providers/themes/*.jar /opt/keycloak/providers

        /opt/keycloak/bin/kc.sh build
        /opt/keycloak/bin/kc.sh start-dev --import-realm

    volumes:
      - ./.docker/keycloak-config/:/opt/keycloak/data/import/:ro
      - spi-theme:/opt/keycloak/providers/themes:ro
    links:
      - prism

  tracking:
    image: jaegertracing/all-in-one:latest
    ports:
      - '4318:4318' # OpenTelemetry receiver
      - '14268:14268' # Jaeger receiver
      - '16686:16686' # Jaeger UI
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'

  # This service downloads the theme from the internet
  download-theme:
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        set -ex;
        wget -O /spi/vymalo-theme.jar https://github.com/vymalo/vymalo-keycloak-theme/releases/download/v2.1.2/theme-2.1.2.jar;
        echo "Downloaded theme";
        ls -la /spi;

        # Keep alive
        tail -f /dev/null
    volumes:
      - spi-theme:/spi

  # This is a mock server for the SMS API
  prism:
    image: stoplight/prism:latest
    ports:
      - '4010:4010'
    command:
      - mock
      - -h
      - 0.0.0.0
      - /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml

volumes:
  spi-theme:
